#===============================================================
#
# This is the DEFAULT setting for aii_in.py.
#
# If you modify settings showed below,
# you should copy this and modify the copied one,
# then pass to all_in.py using --settings (-s) option.
#
# The program assume that there is the "default.yaml"
# in the same directory as all_in.py and "default.yaml" has
# all valid configuration.
# Therefore, changing this file may cause some troubles.
#
# Setting part:
#   logging   - logging and logging.basicConfig in python
#   data      - path to source, destination
#   fastp     - "fastp" parameters
#   assembler - "SKESA", "megahit", "SPAdes" parameters 
#
# ===============================================================


#===============================================================
# logging section
#===============================================================
# You can modify how to create log.
# Be careful, modifying this section perhaps make 
# all_in.py crush without readable log file,
# because logging starts after the program loads this file.

# directory of log files
logging_path: ./log

# filename
filename: all_in.log

# logging level: DEBUG | INFO | WARNING | ERROR
logfile_level: DEBUG
console_level: INFO

# logging config (directly passed to logging.basicConfig)
logging_config: {
 filemode: w,
 format: " %(asctime)s: %(levelname)s(%(name)s):%(message)s",
 datefmt: "%Y/%m/%d %H:%M:%S",
}

#===============================================================
# data section
#===============================================================
# All path should be "relative" path from the repository directory.
data: {
  tag: ["source/R1tag.fasta", "source/R2tag.fasta"],
  primer: ["source/R1primer.fasta", "source/R2primer.fasta"],
  destination: "data",
  datetime_format: "%Y_%m%d_%H%M",
  cells_json: "source/cells.json"
}

#===============================================================
# fastp section
#===============================================================
# You can change parameters in fastp step.
# For more information, please look at the instruction of fastp.

fastp: [
 "-3",
 "-q",
 "30",
 "-n",
 "5",
 "-A"
]
fastp_output: "/var/www/html"

#===============================================================
# assembler section
#===============================================================
# You can change parameters passed to assembler.
# For more information, please consult manuals.

# SKESA parameters
skesa: [
  "--use_paired_ends"
]

# megahit parameters
megahit: [
  "--keep-tmp-files"
]

# SPAdes parameters

#===============================================================
# blast section
#===============================================================
# Here are blastn options.
# For more information, type 
# $ blastn -help
# in your shell.

# blastn parameters
blastn: [
  "-task",
  "blastn",
  "-db",
  "XXXX/XXXX"
]
blastn_header: [
  qaccver,
  saccver,
  pident,
  length,
  mismatch,
  gapopen,
  qstart,
  qend,
  sstart,
  send,
  evalue,
  bitscore
]